DROP TABLE spikee.werknemer_has_uren;
DROP TABLE spikee.team_has_werknemer;
DROP TABLE spikee.uren;
DROP TABLE spikee.team_has_task;
DROP TABLE spikee.fase;
DROP TABLE spikee.task_has_materials;
DROP TABLE spikee.materials;
DROP TABLE spikee.problemen;
DROP TABLE spikee.team;
DROP TABLE spikee.verlof;
DROP TABLE spikee.task;
DROP TABLE spikee.project;
DROP TABLE spikee.klant;
DROP TABLE spikee.werknemer;
DROP TYPE spikee.ENUM_SOORT;
DROP TYPE spikee.ENUM_STAGE;
DROP TYPE spikee.ENUM_PRIORITEIT
