TRUNCATE spikee.werknemer_has_uren;
TRUNCATE spikee.team_has_werknemer;
TRUNCATE spikee.uren;
TRUNCATE spikee.team_has_task;
TRUNCATE spikee.fase;
TRUNCATE spikee.task_has_resources;
TRUNCATE spikee.resources;
TRUNCATE spikee.problemen;
TRUNCATE spikee.klant;
TRUNCATE spikee.werknemer;
TRUNCATE spikee.team;
TRUNCATE spikee.verlof;
TRUNCATE spikee.task;
TRUNCATE spikee.project;


-- DELETE FROM spikee.werknemer_has_uren;
-- DELETE FROM spikee.team_has_werknemer;
-- DELETE FROM spikee.uren;
-- DELETE FROM spikee.team_has_task;
-- DELETE FROM spikee.fase;
-- DELETE FROM spikee.task_has_resources;
-- DELETE FROM spikee.resources;
-- DELETE FROM spikee.problemen;
-- DELETE FROM spikee.klant;
-- DELETE FROM spikee.werknemer;
-- DELETE FROM spikee.team;
-- DELETE FROM spikee.verlof;
-- DELETE FROM spikee.task;
-- DELETE FROM spikee.project;