TRUNCATE werknemer_has_uren;
TRUNCATE team_has_werknemer;
TRUNCATE uren;
TRUNCATE team_has_task;
TRUNCATE fase;
TRUNCATE task_has_resources;
TRUNCATE resources;
TRUNCATE problemen;
TRUNCATE klant;
TRUNCATE werknemer;
TRUNCATE team;
TRUNCATE verlof;
TRUNCATE task;
TRUNCATE project;


-- DELETE FROM werknemer_has_uren;
-- DELETE FROM team_has_werknemer;
-- DELETE FROM uren;
-- DELETE FROM team_has_task;
-- DELETE FROM fase;
-- DELETE FROM task_has_resources;
-- DELETE FROM resources;
-- DELETE FROM problemen;
-- DELETE FROM klant;
-- DELETE FROM werknemer;
-- DELETE FROM team;
-- DELETE FROM verlof;
-- DELETE FROM task;
-- DELETE FROM project;